import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
import "@/styles/index.scss"
import GlobalLayout from "@/layouts/GlobalLayout";
import { ThemeProvider } from "@/hooks/useTheme";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en-US">
      <body>
        <ThemeProvider>
          <GlobalLayout>
          {children}
          </GlobalLayout>
        </ThemeProvider >
      </body>
    </html>
  );
}
